var GAME_LEVELS = [
//recreating first level with real floaters and not coin-wannabes
//"y"=floater "x"=wall "@"=Player "!"=lava "o"=coin
["                                                                                  ",
"    y                                                                             ",
"   yyy              yy                              yy                            ",
"                  yyyy                            yyyyy                            ",
"                                                                                   ",
"  @                         o       xxxxxx                                         ",
"xxxxx                  o xxxxx                                                    ",
"    x                xxxxx   x             !!                                     ",
"    x    o          xxx      x             xx                                     ",//5
"    xxxxxxx     xxxxxx       x!!!!                 !!!          yy                ",
"          x!!!!!x            xxxx!!!!!!!!   !      xxx         yyyy                ",
"          x!!!!!x            xxxxxxxxxx!!   x                                     ",
"          xxxxxxx            xxxxxxxxxx!!!                                          ",
"                                      xxxx                                        ",//10
"                          y                       !!!                             ",
"                         yyy                   o  xxx                             ",
"                       yyyyyy                                                     ",
"                                             !!             !!                    ",
"                                             xx             xx                    ",
"                                                                                  ",//15
"                                                                                    ",
"                                                      o                           ",
"                                            xxxxxx   xxxxxxxx                      ",
"                                                          xxxxx    o   o      o    ",
"                                                                  xx  xxx    xxxxx",
"                                                                   x!!xxx!!!!xxxxx",
"x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxx"], 
 
//level 2
["																					",
"																					",
"									xx												",
"		@							xx												",
"		xxxx			o			xx												",
"	o	xxxxxxxxx					xx												",
"xxxxxxxxxxxxxxxx					xx												",
"			xxxxx			o	s	xx												",
"			xxxxx	o		xxxxxxxxx												",
"			xxxxxxxx																",
"			xxxxx																	",
"			xxxxx		!!!															",
"						xxx															",
"					o																",
"																					",
"			xxxxxxxxxxxxxxxxxx	o													",
"							xx														",
"							xx	o													",
"							xx														",
"							xx	o													",
"							xx										o				",
"							xx	o						xxxxxxxxxxxxx	o			",
"					xxxxxxxxxx							xxxxxx!!!!xxx				",
"					x	=		o					xxxxxxxxx!!!!!xxx				",
"					xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!xxx		o		",
"														!!!!!!!!!!!!!!!!!!!!xx!!!!	",
"																					",
"																					",
"																					",
"																					",
"																					",
"																					",
"																					",
"																					"],


//level 3 I need to make "w" into a spring object!  "q" is super spring! 
["                                                    		                      xxxxxxxx       ",
"                                                           		              		o         ",
"                                                                   		               			",
"                                                                           		   xxxx   		",
"  @                                                yy           			                   		",
"    xxxx                                          yyyyy       			                           	",
"    xxxx                                        yyyyyyy              	                			",
"  o xxxx                                                               		 yy  yy       		",
" xxxxxxx                                                                       yyyyyyyy   	   		",
" xxxxxxxxxxxx                                                                 yyyyyyyyy       	    ",
"  	oo 	 xxxxx                                                                    		       		",
" 	     		                                                                    	   			",
"   oo       		                   s  s  s  s                                              		",
" xxxxxxxxxxxxxxxxxx                 sxxxxxxxxxxxxx                                                 ",
"   o   xxxxxxxxxxxx            	xxxxx=	 o   o                s 					         	",
"   o   xxxxxxxxxxxxxxxx       		xxxx    xxxxxxx   xxxxx   	xxxx	                            ",
"             						xxxx   	 o   o 	  =xxxxx 	xxxx	                            ",
"      				             		  xxxxxxxxxxxxxxxxxx    xxxx      		                    ",
"                                         xxx                 o	xxxx	                      		 ",
"              o     o     xxxxxxxxxxxxxxxx                                         		         ",
"   	o	xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx o                                                        ",
" w			xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx		xxxxxxxxx    		                          	  ",
" xxxxxxxxxxxxxxxxxxxxxxxxxxxx          		    xxxxxxxx                                          ",
"        xxx           	xxxxx		                xxxxxxxxxxxx                                      ",
"        xxx             o   		o       o       x                                       			",
"       xxxx   o    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx               		                          ",
"     	xxxx	                 !!                                                          	  		",
"       xxxx    		!!                     !!                                                  		",
"       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                       			",
"                           		                              xxx                        			",
"                                   		                      xxx  o                       			",
"     		                                                      xxxxxxxxxxxx      q              	  	",
"           		                                                        xxxxxxxxxxxx            	",
"                                           		                                       				"],

//Last Level, Win Screen
["                                                                                  ",
"                                                                                  ",
"                                                                                  ",
"                                                                                  ",
"            xxxx  xxxx  xxxxx    xxxx       xxxx              yy                  ",
"              xx  xx   xx   xx     xx       xx              yyyyy     	           ",
"              xx  xx  xx     xx     xx     xx            yyyyyyyyyy               ",
"              xx  xx  xx     xx     xx     xx                                      ",
"                xx    xx     xx     xx     xx                                       ",
"                xx    xx     xx     xx     xx     yyyy                              ",
"                xx     xx   xx       xx   xx    yyyyyyy                             ",
"               xxxx     xxxxx         xxxxx                                         ",
"                                                                                  ",
"          xxxxx           xxxx xxxxxxx     xxxxx        xxxx                      ",
"            xxx    xx     xxx    xxx        xx xxx      xx                        ",
"             xx    xx     xx     xxx        xx  xx      xx                        ",
"             xx    xx     xx     xxx        xx   xx     xx                        ",
"             xx    xx     xx     xxx        xx    xx    xx                        ",
"     y       xx    xx     xx     xxx        xx     xx   xx                        ",
"    yyy       xx  xx xx  xx      xxx       xxxx      xx xx                        ",
"   yyyyy       xxxx   xxxx     xxxxxxx   xxxxx        xxxx                        ",
"                                                                                  ",
"                                                                                  ",
"                                                                                  ",
"                                                                                  ",
"                                                                                  ",
"                                                                                  "]
];
if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
